fix: Cannot specify more than one extra_container_definitions
terraform-aws-modules/terraform-aws-atlantis pull request #314
Opened 2022-10-19 22:31 UTC by dynamike

## Description
Resolves issues defined in https://github.com/terraform-aws-modules/terraform-aws-atlantis/issues/269 when trying to pass in multiple container definitions into `extra_container_definitions`. The main issue is Terraform's requirement for exact matching objects when untyping a variable as `any` More detail is defined in https://github.com/hashicorp/terraform/issues/26265. This PR leverages required and optional attributes to define a container definition. 

## Motivation and Context
Resolves https://github.com/terraform-aws-modules/terraform-aws-atlantis/issues/269, which seems like an increasingly common issue with more and more sidecar containers used for things like log routing and observability.

## Breaking Changes
There shouldn't be any breaking changes. 

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

2022-10-19 22:42 UTC, bryantbiggs commented on versions.tf
> +  required_version = ">= 1.3.0"
This is a breaking change and we do not want to push users to the bleeding edge as it will reduce adoption

2022-10-19 22:42 UTC, bryantbiggs requested changes
I think we can provide a solution without the need for a breaking change and pushing users to use the latest version of Terraform

2022-10-22 13:09 UTC, bryantbiggs approved these changes

2022-10-22 13:10 UTC, bryantbiggs commented
Thank you @dynamike

2022-10-22 13:10 UTC, merged

2022-10-22 13:11 UTC, antonbabenko commented
This PR is included in version 3.22.1 :tada: